### ISSUE TITLE
Only work one carrousel for page

### ISSUE THREAD

**Issue by JMembri** [leaffm/react-infinite-carousel#11]
The carrousel generate the same id for other components. 

The second carousel not it's showing because are using the same id.

**Comment by JMembri** [comment]
@oyeanuj i think that the problem is in the ID with which the carrousel is generated, because if you can see the code, both have the same id

**Comment by gl0gl0** [comment]
@JMembri  @oyeanuj I have several carousels on a page, and works fine for me. Can you elaborate a little bit more?

**Comment by garrylachman** [comment]
Please re-open... not working well with 2 carousels on a page.
The sec one, the images reloaded from server on any interaction
