### ISSUE TITLE
Carousel not rendering (when no responsive breakpoints are specified) until page is resized

### ISSUE THREAD

**Issue by N-Crofts** [leaffm/react-infinite-carousel#16]
Each li width is somehow being set to 1px until the screen is resized. Once that happens, the width is set to the correct value. Please see screenshot below.

<img width="842" alt="Screen Shot 2019-03-26 at 6 00 42 PM" src="https://user-images.githubusercontent.com/39978815/55036587-7b8c0f80-4ff1-11e9-818e-b00b9a5c45bd.png">

**Comment by Goshishah** [comment]
facing the same issue

**Comment by loading189** [comment]
Having the same issue. Has anyone found a fix?

**Comment by lauraderowitsch** [comment]
was facing the same issue. I added breakpoints settings and the issue stopped occurring. Not really a fix, but if you don't have any, maybe worth a shot?

**Comment by lauraderowitsch** [comment]
was having the same issue. I added breakpoints and the issue stopped occurring. Not exactly a fix, but worth a shot!

**Comment by dkarski** [comment]
It's crazy, but a above suggestion its work in me case 👍

**Comment by gl0gl0** [comment]
Hello all :)
I was able to reproduce this. As @lauraderowitsch says adding breakpoints should solve the problem for now.

Will take a look what's the problem without the breakpoints.

**Comment by gl0gl0** [comment]
This was fixed on latest version `2.0.2`. `responsive` flag is not longer necessary or specifying breakpoints.
