### ISSUE TITLE
Elements does not load properly on mobile view

### ISSUE THREAD

**Issue by cekujin** [leaffm/react-infinite-carousel#23]
Hi, there's a weird behavior in mobile. 

As you can see in the image below, once I've set the viewport and hit refresh. The elements does not seem to load properly.

![image](https://user-images.githubusercontent.com/8220815/64362192-a8ccf700-d040-11e9-9f54-3f3cf101cc96.png)

**Comment by gl0gl0** [comment]
Hi @cekujin 
There's a new version of the component `v2.0.1` in case you want to try. It is working fine in mobile, if you need any more help let me know.
