### ISSUE TITLE
autoCycle doesn't start on component load

### ISSUE THREAD

**Issue by comradecid** [leaffm/react-infinite-carousel#32]
After the component is rendered, cycling between slides doesn't start automatically, despite the 'autoCycle' parameter being set; rather, one has to click on one of the arrows in order to 'kick start' the cycling, which performs as expected thereafter.

Are there plans to fix this issue? Or is there a quick-and-dirty workaround I might be able to employ in the meantime?

**Comment by gl0gl0** [comment]
Hi @comradecid 

Thank you for your question. Are you using version `2.0.2`? I fixed this issue some days ago.

**Comment by comradecid** [comment]
hi there - thanks for getting back to me on this; i did a yarn add and was indeed using the latest version (2.0.2); but to make sure, i did a fresh add and went back and to have another look at the behaviour. 

as before, it doesn't start autocycling on its own, and will happily sit there doing nothing indefinitely if left alone. however, i did notice that _any_ interaction with the rail — including a simple, brief mouse hover — will 'kick' it into cycling 🤷

**Comment by gl0gl0** [comment]
Hi @comradecid!
I just checked and I found out that there was an issue with the .min published package, it wasn't updated properly, I re-publish it, and it should be up and working on `2.0.3`. Sorry for the confusion and thank you! Let me know if it works for you :)

**Comment by gl0gl0** [comment]
I'll be closing this since I haven't heard back yet and I believe is working now. Feel free to reopen if any issues.
Thanks!

**Comment by thebookofjedediah** [comment]
Hi @gl0gl0! I am having this same issue in 2.0.3 where the autoCycle is just not working at all. Any ideas the cause?
