### ISSUE TITLE
2 Carousel Lines

### ISSUE THREAD

**Issue by EliasPiscitelli** [leaffm/react-infinite-carousel#41]
Hello from the beginning tell you that I love the carousel is very easy to use and configure, thanks!
On the other hand, I wanted to know how to do so that instead of one row products are shown in 2 rows one below the other with the same amount of objects.

I am using google translator to write this, apologies in advance if something is not understandable

**Comment by samarth-ramesh** [comment]
@EliasPiscitelli it is a bit late, but here goes:
If you have an array of products, split it into two, display the items in two carousels.
You may probably want some logic that will intelligently add or remove more rows as needed

**Comment by gl0gl0** [comment]
@EliasPiscitelli thanks for your comment! Sorry for the lateness, for the 2 lines I would also try what @samarth-ramesh suggested :)
